name: "Publish module to the PowerShell Gallery"

on: 
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  job-main:
    name: main
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2.3.1

      - name: Install codaamok.build and dependent modules, and set environment variables
        run: |
          Set-PSRepository -Name "PSGallery" -InstallationPolicy Trusted
          Install-Module "InvokeBuild" -Force
          $Username, $ProjectName = $env:GITHUB_REPOSITORY -split "/"
          Invoke-Build -ModuleName $ProjectName -Author $Username -Task "ImportBuildModule","InstallDependentModules","SetGitHubActionEnvironmentVariables"
        shell: pwsh

      - name: Build
        run: Invoke-Build -ModuleName $env:GH_PROJECTNAME -Author $env:GH_USERNAME -CommitMessage $env:GH_COMMITMSG -NewRelease $true
        shell: pwsh

      - name: Publish to PowerShell Gallery
        run: Invoke-Build -ModuleName $env:GH_PROJECTNAME -Task "PublishModule"
        shell: pwsh
        env:
          PSGALLERY_API_KEY: ${{ secrets.PSGALLERY_API_KEY }}

      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.VersionToBuild }}
          release_name: Release ${{ env.VersionToBuild }}
          body_path: release/releasenotes.txt
          draft: false
          prerelease: false

      - name: Upload release asset
        id: upload_release_asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url:  ${{ steps.create_release.outputs.upload_url }}
          asset_path: release/${{ env.GH_PROJECTNAME }}_${{ env.VersionToBuild }}.zip
          asset_name: ${{ env.GH_PROJECTNAME }}_${{ env.VersionToBuild }}.zip
          asset_content_type: application/zip

      - name: Commit CHANGELOG.md and module manifest
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git add CHANGELOG.md ${GH_PROJECTNAME}/${GH_PROJECTNAME}.psd1 docs
          git commit -m "Released ${VersionToBuild}: updated change log and manifest"
      
      - name: Push commit
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}